language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - docker build -t airservice1.1:latest .
  - docker ps -a

deploy:
  provider: script
  script: bash deploy_dockerhub.sh
  on:
    branch: v1.1.2
