language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - docker compose up
  - docker ps -a

deploy:
  provider: script
  script: bash deploy_dockerhub.sh
  on:
    branch: master

#script:
#  - nose2